import Mathlib

namespace VerifyRightUnimodularLatticeImage

/-- The integer lattice generated by the columns of `C`, written explicitly as
its set of attainable integer vectors. -/
def latticeImage {R K : Type*} [Fintype K] (C : Matrix R K ℤ) : Set (R → ℤ) :=
  Set.range C.mulVec

/-- If `Q` has an integral right inverse, changing the coefficient basis by
`C ↦ C Q` preserves the generated integer lattice exactly.  The reverse
inclusion is witnessed by the coefficient change `z ↦ P z`; no norm on the
coefficient coordinates is used. -/
theorem right_unimodular_preserves_lattice_image
    {R K : Type*} [Fintype K] [DecidableEq K]
    (C : Matrix R K ℤ) (Q P : Matrix K K ℤ) (hQP : Q * P = 1) :
    latticeImage (C * Q) = latticeImage C := by
  ext y
  constructor
  · rintro ⟨x, rfl⟩
    refine ⟨Q.mulVec x, ?_⟩
    rw [Matrix.mulVec_mulVec]
  · rintro ⟨z, rfl⟩
    refine ⟨P.mulVec z, ?_⟩
    calc
      (C * Q).mulVec (P.mulVec z) = ((C * Q) * P).mulVec z :=
        Matrix.mulVec_mulVec z (C * Q) P
      _ = (C * (Q * P)).mulVec z := by rw [Matrix.mul_assoc]
      _ = C.mulVec z := by rw [hQP, Matrix.mul_one]

/-- Pointwise membership form of exact lattice-image preservation. -/
theorem right_unimodular_attainable_iff
    {R K : Type*} [Fintype K] [DecidableEq K]
    (C : Matrix R K ℤ) (Q P : Matrix K K ℤ) (hQP : Q * P = 1)
    (y : R → ℤ) :
    (∃ x : K → ℤ, (C * Q).mulVec x = y) ↔
      ∃ z : K → ℤ, C.mulVec z = y := by
  change y ∈ latticeImage (C * Q) ↔ y ∈ latticeImage C
  rw [right_unimodular_preserves_lattice_image C Q P hQP]


/-- Any objective depending only on the lattice output has exactly the same set
of attainable values after the basis change.  Taking `cost y = ‖y-t‖²` is the
CVP specialization; coefficient norms or coefficient supports are
intentionally excluded. -/
theorem right_unimodular_preserves_output_costs
    {R K A : Type*} [Fintype K] [DecidableEq K]
    (C : Matrix R K ℤ) (Q P : Matrix K K ℤ) (hQP : Q * P = 1)
    (cost : (R → ℤ) → A) :
    Set.range (fun x : K → ℤ => cost ((C * Q).mulVec x)) =
      Set.range (fun z : K → ℤ => cost (C.mulVec z)) := by
  ext a
  constructor
  · rintro ⟨x, rfl⟩
    refine ⟨Q.mulVec x, ?_⟩
    change cost (C.mulVec (Q.mulVec x)) = cost ((C * Q).mulVec x)
    exact congrArg cost (Matrix.mulVec_mulVec x C Q)
  · rintro ⟨z, rfl⟩
    refine ⟨P.mulVec z, ?_⟩
    change cost ((C * Q).mulVec (P.mulVec z)) = cost (C.mulVec z)
    apply congrArg cost
    calc
      (C * Q).mulVec (P.mulVec z) = ((C * Q) * P).mulVec z :=
        Matrix.mulVec_mulVec z (C * Q) P
      _ = (C * (Q * P)).mulVec z := by rw [Matrix.mul_assoc]
      _ = C.mulVec z := by rw [hQP, Matrix.mul_one]

/-- With a two-sided integral inverse, the coefficient changes themselves are
mutually inverse.  Thus `C` and `C Q` give bijective parameterizations of the
same lattice (even when the parameterization has a kernel). -/
theorem right_unimodular_coefficient_changes
    {K : Type*} [Fintype K] [DecidableEq K]
    (Q P : Matrix K K ℤ) (hQP : Q * P = 1) (hPQ : P * Q = 1) :
    (∀ z : K → ℤ, Q.mulVec (P.mulVec z) = z) ∧
      ∀ x : K → ℤ, P.mulVec (Q.mulVec x) = x := by
  constructor
  · intro z
    calc
      Q.mulVec (P.mulVec z) = (Q * P).mulVec z :=
        Matrix.mulVec_mulVec z Q P
      _ = z := by rw [hQP, Matrix.one_mulVec]
  · intro x
    calc
      P.mulVec (Q.mulVec x) = (P * Q).mulVec x :=
        Matrix.mulVec_mulVec x P Q
      _ = x := by rw [hPQ, Matrix.one_mulVec]

end VerifyRightUnimodularLatticeImage
