import Mathlib

/-!
# Finite-width butterfly lane closure

This file supplies the finite-width fact omitted by the unbounded lane model:
if a lane is below `2^k` and the butterfly dimension `d` is below `k`, then
XOR by `2^d` is still below `2^k`.  It packages this operation as a map on
`Fin (2^k)`, proves involution and absence of fixed points, and gives a small
smart-event interface whose endpoint pairs are valid by construction.

The scope is only finite lane routing.  No claim is made here about a Python
serializer, token liveness, Boolean gate semantics, integer selectors,
Euclidean energy, or CVP soundness.
-/

namespace VerifyButterflyFiniteWidth

/-- A width-`2^k` lane identifier. -/
abbrev Lane (k : ℕ) := Fin (2 ^ k)

/-- The power of two for a legal physical dimension lies below the width. -/
theorem two_pow_dimension_lt_width {d k : ℕ} (hd : d < k) :
    2 ^ d < 2 ^ k := by
  exact Nat.pow_lt_pow_right (by decide) hd

/-- XOR closure for natural-number lane representatives. -/
theorem xor_dimension_lt_width {lane d k : ℕ}
    (hlane : lane < 2 ^ k) (hd : d < k) :
    lane ^^^ (2 ^ d) < 2 ^ k := by
  exact Nat.xor_lt_two_pow hlane (two_pow_dimension_lt_width hd)

/-- The neighbor of a finite lane in a legal butterfly dimension.  Taking the
 dimension as `Fin k` makes `d < k` part of the input's type. -/
def neighbor {k : ℕ} (d : Fin k) (lane : Lane k) : Lane k :=
  ⟨lane.val ^^^ (2 ^ d.val),
    xor_dimension_lt_width lane.isLt d.isLt⟩

@[simp] theorem neighbor_val {k : ℕ} (d : Fin k) (lane : Lane k) :
    (neighbor d lane).val = lane.val ^^^ (2 ^ d.val) := rfl

/-- Every finite-width butterfly edge can be traversed in both directions. -/
theorem neighbor_involutive {k : ℕ} (d : Fin k) :
    Function.Involutive (neighbor d) := by
  intro lane
  apply Fin.ext
  simp [neighbor]

/-- XOR by a legal (hence nonzero) power of two has no fixed finite lane. -/
theorem neighbor_ne {k : ℕ} (d : Fin k) (lane : Lane k) :
    neighbor d lane ≠ lane := by
  intro h
  have hx : lane.val ^^^ (2 ^ d.val) = lane.val ^^^ 0 := by
    simpa [neighbor] using congrArg Fin.val h
  have hz : 2 ^ d.val = 0 := Nat.xor_right_inj.mp hx
  exact (Nat.two_pow_pos d.val).ne' hz

/-- The reverse endpoint is the original lane. -/
@[simp] theorem neighbor_neighbor {k : ℕ} (d : Fin k) (lane : Lane k) :
    neighbor d (neighbor d lane) = lane :=
  neighbor_involutive d lane

/-- Abstract finite-lane routing events after their endpoints have been
 elaborated. -/
inductive Event (k : ℕ) where
  | wait
  | swap (a b : Lane k)
  | duplicate (source destination : Lane k)
  | nandZero (output consumed : Lane k)
  | cleanup (root : Lane k)
  deriving DecidableEq

/-- Local adjacency and distinctness obligations for a routed event.  WAIT and
 cleanup do not read a B input. -/
def Event.Valid {k : ℕ} (next : Lane k → Lane k) : Event k → Prop
  | .wait => True
  | .swap a b => a ≠ b ∧ next a = b
  | .duplicate source destination =>
      source ≠ destination ∧ next destination = source
  | .nandZero output consumed =>
      output ≠ consumed ∧ next output = consumed
  | .cleanup _ => True

/-- An elaborated event carries its physical finite-width neighbor map. -/
structure ScheduledEvent (k : ℕ) where
  next : Lane k → Lane k
  event : Event k

/-- Full local routing validity: involutive physical pairing plus event-local
 adjacency. -/
def ScheduledEvent.Valid {k : ℕ} (scheduled : ScheduledEvent k) : Prop :=
  Function.Involutive scheduled.next ∧ scheduled.event.Valid scheduled.next

/-- A smart event stores only one endpoint and a legal dimension.  Its other
 endpoint is generated by `neighbor`, so an out-of-width or non-adjacent edge
 cannot be represented. -/
inductive SmartEvent (k : ℕ) where
  | wait (d : Fin k)
  | swap (d : Fin k) (lane : Lane k)
  | duplicate (d : Fin k) (destination : Lane k)
  | nandZero (d : Fin k) (output : Lane k)
  | cleanup (d : Fin k) (root : Lane k)
  deriving DecidableEq

/-- Elaborate a finite-width smart event into explicit endpoints. -/
def SmartEvent.schedule {k : ℕ} : SmartEvent k → ScheduledEvent k
  | .wait d => ⟨neighbor d, .wait⟩
  | .swap d lane => ⟨neighbor d, .swap lane (neighbor d lane)⟩
  | .duplicate d destination =>
      ⟨neighbor d, .duplicate (neighbor d destination) destination⟩
  | .nandZero d output =>
      ⟨neighbor d, .nandZero output (neighbor d output)⟩
  | .cleanup d root => ⟨neighbor d, .cleanup root⟩

/-- Smart finite-width events satisfy involution, adjacency, and endpoint
 distinctness without an external validity hypothesis. -/
theorem SmartEvent.schedule_valid {k : ℕ} (event : SmartEvent k) :
    event.schedule.Valid := by
  cases event with
  | wait d => exact ⟨neighbor_involutive d, trivial⟩
  | swap d lane =>
      exact ⟨neighbor_involutive d, (neighbor_ne d lane).symm,
        rfl⟩
  | duplicate d destination =>
      exact ⟨neighbor_involutive d, neighbor_ne d destination,
        rfl⟩
  | nandZero d output =>
      exact ⟨neighbor_involutive d, (neighbor_ne d output).symm,
        rfl⟩
  | cleanup d root => exact ⟨neighbor_involutive d, trivial⟩

/-- Elaborate a whole smart finite-width trace. -/
def scheduleTrace {k : ℕ} (trace : List (SmartEvent k)) :
    List (ScheduledEvent k) :=
  trace.map SmartEvent.schedule

/-- Every stage in an elaborated smart trace is locally valid. -/
theorem scheduleTrace_all_valid {k : ℕ} (trace : List (SmartEvent k)) :
    ∀ scheduled ∈ scheduleTrace trace, scheduled.Valid := by
  intro scheduled hmem
  simp only [scheduleTrace, List.mem_map] at hmem
  rcases hmem with ⟨event, _hevent, rfl⟩
  exact event.schedule_valid

end VerifyButterflyFiniteWidth
